//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL6b
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        public int Id { get; set; }
        public string Sobrenome { get; set; }
        public int MembroId { get; set; }
        public double Renda { get; set; }
    
        public virtual Membro Membro { get; set; }
    }
}
